version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 2
  reviewers:
  - benjello
  ignore:
  - dependency-name: pycodestyle
    versions:
    - 2.6.0
