# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-python/>.
version: 2
jobs:
  build:
    parallelism: 2  # Speed up the tests, while letting two containers available for other builds.
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-deps-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca_mali
            python -m venv /tmp/venv/openfisca_mali
            echo "source /tmp/venv/openfisca_mali/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            make build
            # pip install --editable git+https://github.com/openfisca/openfisca-core.git@BRANCH_NAME#egg=OpenFisca-Core  # use a specific branch of OpenFisca-Core

      - save_cache:
          key: v1-py3-deps-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca_mali

      - save_cache:
          key: v1-py3-build-{{ .Revision }}
          paths:
            - dist

      - run:
          name: Run tests
          command: |
            pytest `circleci tests glob "openfisca_mali/tests/[^_]*.py" | circleci tests split`
            # openfisca test -c openfisca_mali openfisca_mali/tests/formulas/*.yaml  # This one works
            openfisca test `circleci tests glob "openfisca_mali/tests/formulas/*.yaml" | circleci tests split`
            # openfisca test `circleci tests glob "openfisca_mali/tests/**/*.{yaml,yml}" | circleci tests split`  # Target

  lint_yaml_files:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-deps-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Activate virtualenv
          command: |
            echo "source /tmp/venv/openfisca_mali/bin/activate" >> $BASH_ENV

      - run:
          name: Lint files
          command: |
            .circleci/lint-changed-yaml-tests.sh

  lint_python_files:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-deps-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Activate virtualenv
          command: |
            echo "source /tmp/venv/openfisca_mali/bin/activate" >> $BASH_ENV

      - run:
          name: Lint files
          command: |
            make check-syntax-errors check-style
            .circleci/lint-changed-python-files.sh

  check_version_and_changelog:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            .circleci/is-version-number-acceptable.sh

  deploy:
    docker:
      - image: python:3.7
    environment:
      PYPI_USERNAME: openfisca-bot
      # PYPI_PASSWORD: this value is set in CircleCI's web interface; do not set it here, it is a secret!

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-deps-{{ .Branch }}-{{ checksum "setup.py" }}

      - restore_cache:
          key: v1-py3-build-{{ .Revision }}

      - run:
          name: Check for functional changes
          command: if ! .circleci/has-functional-changes.sh ; then circleci step halt ; fi

      - run:
          name: Upload a Python package to Pypi
          command: |
            source /tmp/venv/openfisca_mali/bin/activate
            twine upload dist/* --username $PYPI_USERNAME --password $PYPI_PASSWORD

      - run:
          name: Publish a git tag
          command: .circleci/publish-git-tag.sh

      - run:
          name: Deploy the Web API
          command: ssh -o StrictHostKeyChecking=no deploy-api@fr.openfisca.org

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - check_version_and_changelog
      - build
      - lint_yaml_files:
          requires:
            - build
      - lint_python_files:
          requires:
            - build
      - deploy:
          requires:
            - check_version_and_changelog
            - build
            - lint_yaml_files
            - lint_python_files
          filters:
            branches:
              only: master
